# docker-compose.yml

version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: laravel_breeze_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ..:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "9000:9000"
      - "8000:8000"
    depends_on:
      - db
      - opensearch
    command: bash -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: laravel_breeze_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:18
    container_name: laravel_breeze_node
    working_dir: /var/www
    volumes:
      - ..:/var/www
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev"
    
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: laravel_breeze_opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
      - network.host=0.0.0.0
      - http.port=9200
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  init-opensearch:
    image: curlimages/curl:latest
    container_name: init_opensearch
    entrypoint: ["sh", "-c"]
    command: >
      "
        until curl -s http://opensearch:9200; do
          echo 'Waiting for OpenSearch...';
          sleep 5;
        done;
        curl -X PUT 'http://opensearch:9200/places' -H 'Content-Type: application/json' -d'
        {
          \"mappings\": {
            \"properties\": {
              \"location\": { \"type\": \"geo_point\" }
            }
          }
        }
        '
      "
    depends_on:
      - opensearch

volumes:
  db_data:
  opensearch_data: