# docker-compose.yml

version: '3.8'
services:
  app:
    image: laraplaces
    container_name: laravel_breeze_app
    restart: unless-stopped
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db
      - opensearch

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver-dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ..:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_breeze_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: laravel_breeze_opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
      - network.host=0.0.0.0
      - http.port=9200
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - laravel

  init-opensearch:
    image: curlimages/curl:latest
    container_name: init_opensearch
    entrypoint: ["sh", "-c"]
    command: >
      "
        until curl -s http://opensearch:9200; do
          echo 'Waiting for OpenSearch...';
          sleep 5;
        done;
        curl -X PUT 'http://opensearch:9200/places' -H 'Content-Type: application/json' -d'
        {
          \"mappings\": {
            \"properties\": {
              \"location\": { \"type\": \"geo_point\" }
            }
          }
        }
        '
      "
    depends_on:
      - opensearch
    networks:
      - laravel

volumes:
  db_data:
  opensearch_data:

networks:
  laravel:
    driver: bridge
